#!/bin/bash

export AMOK=$(git describe --tags $(git rev-list --tags --max-count 1))
echo "Setting version to $AMOK"
for FILE in src/*/*.scala
do
  echo "Updating header in $FILE"
  cat etc/header.txt | envsubst > .tmpfile
  sed '/package/,$!d' "${FILE}" >> .tmpfile && mv .tmpfile "${FILE}"
done
